#!/usr/bin/with-contenv sh
. "/usr/local/bin/logger"
# ==============================================================================
# cloudupload
# Uploads local-decrypt to cloud
# ==============================================================================

/bin/s6-svwait -U /var/run/s6/services/media

# Dedupe Google Drive with defined location
echo "###### Begin Dedupe ######" | info
if [ "${DEDUPE_CLOUD_DECRYPT}" == "1" ]; then
  echo "Deduping cloud-decrypt at ${RCLONE_CLOUD_DECRYPT_REMOTE}:" | info
  rclone dedupe \
    --config=/tmp/rcloneconfig/rclone.conf \
    ${DEDUPE_OPTIONS} \
    "${RCLONE_CLOUD_DECRYPT_REMOTE}:"
  echo "Deduping Google Drive at ${RCLONE_CLOUD_DECRYPT_REMOTE} Complete" | info
fi
if [ "${DEDUPE_MIRROR_REMOTE}" == "1" ]; then
	echo "Deduping mirror remote at ${RCLONE_MIRROR_DECRYPT_REMOTE}:" | info
	rclone dedupe \
	  --config=/tmp/rcloneconfig/rclone.conf \
	  ${DEDUPE_OPTIONS} \
	  "${RCLONE_MIRROR_DECRYPT_REMOTE}:"
	echo "Deduping Google Drive at ${RCLONE_MIRROR_DECRYPT_REMOTE} Complete" | info
fi
echo "###### Dedupe Completed ######" | info
