#!/command/with-contenv sh
. "/usr/local/bin/logger"
# ==============================================================================
# cloudupload
# Uploads local-decrypt to cloud
# ==============================================================================

_term() {
  kill -TERM "$child" 2>/dev/null
  exit
}

trap _term SIGTERM

s6-svwait -U /run/service/media

# Dedupe Google Drive with defined location
echo "###### Begin Dedupe ######" | info
if [ "${DEDUPE_CLOUD_DECRYPT}" -eq 1 ]; then
  echo "Deduping cloud-decrypt at ${RCLONE_CLOUD_DECRYPT_REMOTE}:" | info
  fdmove 2 1 \
    rclone dedupe \
      --config=/config/rclone.conf \
      ${DEDUPE_OPTIONS} \
      "${RCLONE_CLOUD_DECRYPT_REMOTE}:" &
  child=$!
  wait "$child"
  echo "Deduping Google Drive at ${RCLONE_CLOUD_DECRYPT_REMOTE} Complete" | info
fi
if [ "${DEDUPE_MIRROR_REMOTE}" -eq 1 ]; then
	echo "Deduping mirror remote at ${RCLONE_MIRROR_DECRYPT_REMOTE}:" | info
	fdmove 2 1 \
	  rclone dedupe \
      --config=/config/rclone.conf \
      ${DEDUPE_OPTIONS} \
      "${RCLONE_MIRROR_DECRYPT_REMOTE}:" &
  child=$!
  wait "$child"
	echo "Deduping Google Drive at ${RCLONE_MIRROR_DECRYPT_REMOTE} Complete" | info
fi
echo "###### Dedupe Completed ######" | info
