#!/usr/bin/with-contenv sh
. "/usr/local/bin/logger"
# ==============================================================================
# cloudupload
# Uploads local-decrypt to cloud
# ==============================================================================

/bin/s6-svwait -U /var/run/s6/services/media

check_rclone_cloud
check_rclone_mirror

# Syncing Google Drive with mirror endpoint
echo "[ $(date $(printenv DATE_FORMAT)) ] ###### Begin Mirror ######"
echo "[ $(date $(printenv DATE_FORMAT)) ] Syncing from ${rclone_cloud_encrypted_endpoint} to ${rclone_mirror_encrypted_endpoint}"
rclone sync $rclone_mirror_options "${rclone_cloud_encrypted_endpoint}" "${rclone_mirror_encrypted_endpoint}"
echo "[ $(date $(printenv DATE_FORMAT)) ] Sync from ${rclone_cloud_encrypted_endpoint} to ${rclone_mirror_encrypted_endpoint} Complete"
echo "[ $(date $(printenv DATE_FORMAT)) ] ###### Mirror Completed ######"

# success!
exit 0
