#!/usr/bin/with-contenv sh
. "/usr/local/bin/logger"
# ==============================================================================
# cloudupload
# Uploads local-decrypt to cloud
# ==============================================================================

_term() {
  kill -TERM "$child" 2>/dev/null
  exit
}

trap _term SIGTERM

/bin/s6-svwait -U /var/run/s6/services/media
rclone_mirror_encrypted_endpoint="${MIRROR_ENCRYPTED_ENDPOINT}:${MIRROR_SUBDIR}" # use encrypted mount so server side copying works
rclone_cloud_encrypted_endpoint="${CLOUD_ENCYPTED_ENDPOINT}:${MIRROR_SUBDIR}"

# Syncing Google Drive with mirror endpoint
echo "###### Begin Mirror ######" | info
echo "Syncing from ${rclone_cloud_encrypted_endpoint} to ${rclone_mirror_encrypted_endpoint}" | info
rclone sync \
  --config=/tmp/rcloneconfig/rclone.conf \
  ${MIRROR_OPTIONS} \
  "${rclone_cloud_encrypted_endpoint}" \
  "${rclone_mirror_encrypted_endpoint}" &
child=$!
wait "$child"
echo "Sync from ${rclone_cloud_encrypted_endpoint} to ${rclone_mirror_encrypted_endpoint} Complete" | info
echo "###### Mirror Completed ######" | info
