#!/usr/bin/with-contenv sh
. "/usr/local/bin/logger"
# ==============================================================================
# media
# Take down the S6 supervision tree if media goes down
# ==============================================================================

echo "Terminating media..." | info
fusermount -uz /mounts/media
s6-svscanctl -t /var/run/s6/services
