#!/usr/bin/with-contenv sh
# ==============================================================================
# media
# Take down the S6 supervision tree if media goes down
# ==============================================================================

s6-svscanctl -t /var/run/s6/services
