#!/usr/bin/with-contenv sh
. "/usr/local/bin/logger"
# ==============================================================================
# media
# Mounts the media directory (final merged directory) using mergerfs
# ==============================================================================

if [ "${RCLONE_MOUNT_LOCAL_DECRYPT}" -eq "1" ]; then
  /bin/s6-svc -u /var/run/s6/services/local-decrypt
  /bin/s6-svwait -U /var/run/s6/services/local-decrypt
fi
/bin/s6-svwait -U /var/run/s6/services/cloud-decrypt

# Need to ensure that media isn't currently mounted before mounting
fusermount -uz /data/media > /dev/null 2>&1

echo "Mounting media..." | info

set -x
exec s6-notifyoncheck -n 1000 \
      fdmove 2 1 \
        mergerfs -f \
        -o uid="${PUID:-911}" -o gid="${PGID:-911}" \
        -o "${MERGERFS_OPTIONS}" \
        /mounts/local-decrypt:/mounts/cloud-decrypt \
        /data/media
