#!/command/with-contenv sh
. "/usr/local/bin/logger"
# ==============================================================================
# media
# Mounts the media directory (final merged directory) using mergerfs
# ==============================================================================

if [ "${RCLONE_MOUNT_LOCAL_DECRYPT}" -eq "1" ]; then
  s6-svc -u /run/service/local-decrypt
  s6-svwait -U /run/service/local-decrypt
fi
s6-svwait -U /run/service/cloud-decrypt

echo "Mounting media..." | info

set -x
exec s6-notifyoncheck -n 1000 \
      fdmove 2 1 \
        mergerfs -f \
        -o uid="${PUID:-911}" -o gid="${PGID:-911}" \
        -o "${MERGERFS_OPTIONS}" \
        /mounts/local-decrypt:/mounts/cloud-decrypt=NC \
        /data/mnt
