#!/usr/bin/with-contenv sh
. "/usr/local/bin/logger"
# ==============================================================================
# precache
# Caches cloud directory
# ==============================================================================

# Reconfigure to be oneshot
/bin/s6-svc -O /var/run/s6/services/precache

/bin/s6-svwait -U /var/run/s6/services/cloud-decrypt

if [ "${PRECACHE_ENABLED}" -eq 1 ]; then
  if [ "${PRECACHE_USE_RC}" -eq 1 ]; then
    if [ -z "${PRECACHE_VFS_DIR}" ]; then
      echo "Running precache using vfs/refresh for the entire mount..." | info
      s6-setuidgid abc rclone rc --config=/config/rclone.conf vfs/refresh recursive=true
    else
      echo "Running precache using vfs/refresh for dir=${PRECACHE_VFS_DIR}..." | info
      s6-setuidgid abc rclone rc --config=/config/rclone.conf vfs/refresh dir="${PRECACHE_VFS_DIR}" recursive=true
    fi
  else
    echo "Running precache using find..." | info
    /usr/bin/find "${PRECACHE_FIND_DIR}"
  fi
  echo "Precache complete!" | info
fi
