#!/usr/bin/with-contenv sh

if df -P -T | grep /mounts/local-decrypt | awk '{print $2}' | grep fuse\.rclone > /dev/null; then
    exit # local-decrypt is mounted
fi
exit 1 # local-decrypt is not mounted