#!/command/with-contenv sh
# ==============================================================================
# local-decrypt
# Take down the S6 supervision tree if local-decrypt goes down
# ==============================================================================

/run/s6/basedir/bin/halt
