#!/usr/bin/with-contenv sh
. "/usr/local/bin/logger"
# ==============================================================================
# local-decrypt
# Mounts the local-decrypt directory (decrypted local files) using rclone
# ==============================================================================

echo "Mounting local-decrypt from "\
  "${RCLONE_LOCAL_DECRYPT_REMOTE}:${RCLONE_LOCAL_DECRYPT_DIR}" \
   "to /mounts/local-decrypt ..." | info

exec fdmove -c 1 3 \
  rclone mount \
    "${RCLONE_LOCAL_DECRYPT_REMOTE}:${RCLONE_LOCAL_DECRYPT_DIR}" \
    /mounts/local-decrypt
