#!/command/with-contenv sh
. "/usr/local/bin/logger"
# ==============================================================================
# local-decrypt
# Mounts the local-decrypt directory (decrypted local files) using rclone
# ==============================================================================

echo "Mounting local-decrypt..." | info

set -x
exec s6-notifyoncheck -n 1000 \
      fdmove -c 2 1 \
        rclone mount \
          --config=/config/rclone.conf \
          -v \
          "${RCLONE_LOCAL_DECRYPT_REMOTE}:${RCLONE_LOCAL_DECRYPT_DIR}" \
          /mounts/local-decrypt
