#!/command/with-contenv sh

if df -P -T | grep /mounts/cloud-decrypt | awk '{print $2}' | grep fuse\.rclone > /dev/null; then
    exit # cloud-decrypt is mounted
fi
exit 1 # cloud-decrypt is not mounted