#!/command/with-contenv sh
. "/usr/local/bin/logger"
# ==============================================================================
# Crond
# Runs crond to execute background jobs cloudupload, dedupe, emptytrash, mirror, and rmlocal
# ==============================================================================

echo "Starting crond..." | info

exec /usr/sbin/crond -f
