#!/usr/bin/with-contenv sh
. "/usr/local/bin/logger"
# ==============================================================================
# cloud-decrypt
# Take down the S6 supervision tree if local-decrypt goes down
# ==============================================================================

echo "Terminating cloud-decrypt..." | info
fusermount -uz /mounts/cloud-decrypt
s6-svscanctl -t /var/run/s6/services
