#!/usr/bin/with-contenv sh
. "/usr/local/bin/logger"
# ==============================================================================
# cloud-decrypt
# Mounts the cloud-decrypt directory (decrypted cloud files) using rclone
# ==============================================================================

cloud_decrypt_remote="${RCLONE_CLOUD_DECRYPT_REMOTE}"
cloud_decrypt_dir="${RCLONE_CLOUD_DECRYPT_DIR}"

if [ "${RCLONE_USE_MIRROR_AS_CLOUD_REMOTE}" == "1" ]; then
  cloud_decrypt_remote="${RCLONE_MIRROR_DECRYPT_REMOTE}"
  cloud_decrypt_dir="${RCLONE_MIRROR_DECRYPT_DIR}"
fi

echo "Mounting cloud-decrypt..." | info

set -x

exec s6-notifyoncheck -n 1000 \
      fdmove 2 1 \
        rclone mount \
          --config=/config/rclone.conf \
          --allow-other \
          --uid "${PUID:-911}" \
          --gid "${PGID:-911}" \
          --umask "${RCLONE_MASK}" \
          ${RCLONE_VFS_READ_OPTIONS} \
          "${cloud_decrypt_remote}:${cloud_decrypt_dir}" \
          /mounts/cloud-decrypt
