#!/usr/bin/with-contenv sh
. "/usr/local/bin/logger"
# ==============================================================================
# cloud-decrypt
# Mounts the cloud-decrypt directory (decrypted cloud files) using rclone
# ==============================================================================

cloud_decrypt_remote="${RCLONE_CLOUD_DECRYPT_REMOTE}"
cloud_decrypt_dir="${RCLONE_CLOUD_DECRYPT_DIR}"

if [ "${RCLONE_USE_MIRROR_AS_CLOUD_REMOTE}" == "1" ]; then
  cloud_decrypt_remote="${RCLONE_MIRROR_REMOTE}"
  cloud_decrypt_dir="${RCLONE_MIRROR_DIR}"
fi

echo "Mounting cloud-decrypt..." | info

set -x

# Move stdout to 3 to notify s6 of readiness
exec fdmove 2 1 \
      fdmove -c 1 3 \
        rclone mount \
          --config=/tmp/rcloneconfig/rclone.conf \
          --allow-other \
          --uid "${PUID:-911}" \
          --gid "${PGID:-911}" \
          --umask "${RCLONE_MASK}" \
          ${RCLONE_VFS_READ_OPTIONS} \
          "${cloud_decrypt_remote}:${cloud_decrypt_dir}" \
          /mounts/cloud-decrypt
