name: Deploy

on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - uses: actions/checkout@v2
      - name: Build Image
        id: build_image
        run: |
          docker build -t yaoa/cloud-media-scripts:ci -f ./Dockerfile .
      - name: Save tarball
        run: |
          docker save --output output.tar yaoa/cloud-media-scripts:ci
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: ci-${{ github.run_number }}.tar
          path: output.tar
  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    name: Deploy
    strategy:
      matrix:
        registry: [dockerhub, ghcr]
    steps:
      - name: Download container artifact
        uses: actions/download-artifact@v2
        with:
          name: ci-${{ github.run_number }}.tar
      - name: Set Docker Repository & Load Image
        run: |
          docker load --input output.tar
          if [ ${{ matrix.registry }} == "dockerhub" ]; then
            export DOCKER_REPO="yaoa/cloud-media-scripts"
          else
            export DOCKER_REPO="ghcr.io/alexyao2015/cloud-media-scripts/core"
          fi
          echo "DOCKER_REPO=${DOCKER_REPO}" >> $GITHUB_ENV
          echo Repository set as: ${DOCKER_REPO}
      - name: Login
        run: |
          if [ ${{ matrix.registry }} == "dockerhub" ]; then
            docker login -u ${{ secrets.dockerID }} -p ${{ secrets.dockerPassword }}
          else
            echo "${{ secrets.CR_PAT }}" | docker login ghcr.io/alexyao2015 -u "${{ secrets.CR_USER }}" --password-stdin
          fi
      - name: Deploy Commit ID
        if: ${{ github.head_ref == '' && github.sha != '' }}
        run: |
          docker tag yaoa/cloud-media-scripts:ci ${DOCKER_REPO}:$GITHUB_SHA
          docker push ${DOCKER_REPO}:$GITHUB_SHA
      - name: Deploy Run Number
        if: ${{ github.head_ref == '' && github.sha != '' }}
        run: |
          docker tag yaoa/cloud-media-scripts:ci ${DOCKER_REPO}:$GITHUB_RUN_NUMBER
          docker push ${DOCKER_REPO}:$GITHUB_RUN_NUMBER
      - name: Deploy Latest
        if: ${{ github.head_ref == '' && github.ref == 'refs/heads/master' }}
        run: |
          docker tag yaoa/cloud-media-scripts:ci ${DOCKER_REPO}:latest
          docker push ${DOCKER_REPO}:latest
      - name: Deploy Develop
        if: ${{ github.head_ref == '' && startsWith(github.ref, 'refs/heads/dev') }}
        run: |
          docker tag yaoa/cloud-media-scripts:ci ${DOCKER_REPO}:latest-develop
          docker push ${DOCKER_REPO}:latest-develop
      - name: Deploy Branch
        if: ${{ github.head_ref == '' && startsWith(github.ref, 'refs/heads/') }}
        run: |
          docker tag yaoa/cloud-media-scripts:ci ${DOCKER_REPO}:${GITHUB_REF##*/}
          docker push ${DOCKER_REPO}:${GITHUB_REF##*/}
      - name: Deploy Tag
        if: ${{ github.head_ref == '' && startsWith(github.ref, 'refs/tags/') }}
        run: |
          docker tag yaoa/cloud-media-scripts:ci ${DOCKER_REPO}:${GITHUB_REF##*/}
          docker push ${DOCKER_REPO}:${GITHUB_REF##*/}
